### ISSUE TITLE
Haven't got a digest in a while

### ISSUE THREAD

**Issue by steveoh** [probot/weekly-digest#65] opened 2018-10-02 18:02 UTC
22 days. Did something change? Do I need to modify my config or something? repo is https://github.com/agrc/gis.utah.gov

**Comment by brad-decker** [comment] 2018-10-06 21:37
Confirmed it stopped working for us too.

**Comment by abhijeetps** [comment] 2018-10-08 14:34
Hi @steveoh , @brad-decker ,
Thanks for opening this issue. 
Please have a look at this: https://github.com/search?o=desc&q=Weekly+Digest&s=created&type=Issues

You might be seeing that Weekly Digest is working fine for these repositories. 

Is it possible to share the repository where you have installed the application so that I can have a look at it?

Try reinstalling app in your repository once. Also, the configuration is optional. Weekly Digest will work fine without configuring _.github/weekly-digest.yml_.

If the problem persists, please let me know so that I can trace the bug behind it. Currently, I cannot retrace the bug.

Please suggest some more features that you would like to see in the weekly digest app. 😄

**Comment by steveoh** [comment] 2018-10-08 16:35
I left the repo link in my comment. I'll try the uninstall reinstall option

**Comment by steveoh** [comment] 2018-10-10 01:43
I think my issue is that you changed publish day from an integer to a day abbreviation at some point.

**Comment by abhijeetps** [comment] 2018-10-10 07:57
@steveoh , Yeah, I saw that you made some changes in that repository: https://github.com/agrc/gis.utah.gov/commit/b38916415830cab92380054eeb97fb141b090f83

And looks like it's working fine now: https://github.com/agrc/gis.utah.gov/issues/962 🎉 

I made the app to understand both numeric and alphabetical dates and work properly, but I am not sure what went wrong. I will look again into it. 👀 

Sorry for the inconvenience caused. 🙏

**Comment by abhijeetps** [comment] 2018-10-10 07:58
@brad-decker , maybe you might be facing the same problem, can you once check it out and update if the problem persists.
Thanks. 😄

**Comment by brad-decker** [comment] 2018-10-15 15:55
So i deleted the install, then reinstalled it. Same issue. I got the initial weekly digest but then sunday came and went without an update. is a config file now required? @abhijeetps

**Comment by steveoh** [comment] 2018-10-15 16:03
Mine is set to publish monday so if nothing shows up tonight or tomorrow morning, then there is an issue up stream.

**Comment by abhijeetps** [comment] 2018-10-15 16:07
@brad-decker , Adding `weekly-digest.yml` for config is an optional feature. It works by default if the configuration is not defined.

@steveoh , I am watching your repository closely, the app should publish weekly digest, if it won't, I will ask the my mentor about the issue.

**Comment by abhijeetps** [comment] 2018-10-15 16:13
Here's the recent Weekly Digest, being published by app on many repositories (on Sunday), for example: https://github.com/search?o=desc&q=Weekly+Digest&s=created&type=Issues

**Comment by maestromac** [comment] 2018-10-15 17:48
I'm also not getting the weekly update. I receive the first digest and that was it. This is me [fiddling around with the setting](https://github.com/thepracticaldev/dev.to/commits/master/.github/weekly-digest.yml) trying to evoke it. Any tips?

**Comment by maestromac** [comment] 2018-10-29 15:56
re-adding solved it. This bug might have something to do with updating the .yml file.

**Comment by steveoh** [comment] 2018-10-29 16:16
I haven't got a digest in a while. What was your solution?

**Comment by maestromac** [comment] 2018-10-29 16:20
What I did was.
1. Remove `.github/weekly-digest.yml`
2. Remove the Weekly Digest integration
3. Re-add Weekly Digest integration
4. Re-add `.github/weekly-digest.yml`

**Comment by steveoh** [comment] 2018-10-29 20:12
Ok I just tried your steps. We'll see how my mileage varies.

**Comment by steveoh** [comment] 2018-11-07 18:15
Still no digest. I don't know how to make this work. What is special about my repo?

**Comment by maestromac** [comment] 2018-11-07 18:31
Mine stop working too ☹️

**Comment by abhijeetps** [comment] 2018-11-07 18:45
I have opened a discussion here on Slack: https://probot-talk.slack.com/archives/C6S4FC8AF/p1541616078059300
I too can't figure out the reason behind the app not working fine on few repositories. I hope someone from Probot will help me with this. 
I will let you know if I receive any updates.

**Comment by abhijeetps** [comment] 2018-11-19 07:33
Hey, just a minor update on my progress of trying to figure out why the app is not working on some repositories.
I was checking out logs and found the following error:

```
ERROR event: {"message":"API rate limit exceeded for installation ID XXXXXX.","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
  HttpError: {"message":"API rate limit exceeded for installation ID XXXXXX.","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
      at response.text.then.message (/home/nowuser/src/node_modules/@octokit/rest/lib/request/request.js:72:19)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  
  event: {
    "event": "schedule.repository",
    "installation": XXXXXX,
    "repository": "owner/repository"
  }
```

I will try to figure out with Probot and GitHub team of how I can work with this problem. 
As the popularity of this app is increasing, this app might need more requests in future, and needs a strong solution for the same.

I will keep you updated about this more. 
Thank you for using Weekly Digest app. 😄

**Comment by steveoh** [comment] 2019-01-09 15:57
Any love on this lately?

**Comment by yangwenmai** [comment] 2019-01-27 04:32
> @abhijeetps Please help me when you're not busy.

Now, It's work for [my repos](https://github.com/developer-learning/night-reading-go)

**Comment by abhijeetps** [comment] 2019-01-28 04:50
@yangwenmai , it's really good to see that it works on your repository.
Though, probably you might still face some problem with it as Sunday is a pretty busy day for Weekly Digest app.

**Comment by abhijeetps** [comment] 2019-01-28 04:55
@steveoh , I know you were among the first users of my Weekly Digest application, and I feel really bad that it's not working on your repo. :(
I have seen that you have even tried changing days but still, it's not working out.
But, one thing that I am pretty sure of is that it not a problem in your end, there's some bug in the app only which is holding it from publishing weekly digests for your repo.
I am trying to find out a bug for the same, but still, I have no clue, what the bug is. I think I will have to try debug the code and spend a day at the logs to check the problem behind it. 😄

**Comment by yangwenmai** [comment] 2019-01-29 13:57
> @yangwenmai , it's really good to see that it works on your repository.
> Though, probably you might still face some problem with it as Sunday is a pretty busy day for Weekly Digest app.
> I recommend you to add _.github/weekly-digest.yml_ file and configure your app to publish weekly digest on some other day.

I set thurday, and i will take a look in that day.

**Comment by abhijeetps** [comment] 2019-02-04 12:46
Hey @steveoh , sorry for the ping again.
But it looks like the Weekly Digest app has started working fine on your repository again for the second time from my last message.
See: https://github.com/agrc/gis.utah.gov/issues/1020

Since it has started working again normally without any changes done on my end, I think I can say that it was some problem with GitHub APIs.

I will close this issue now.

Also, I have a piece of good news that I would like to share. Week;y Digest now has over 5000 Weekly Digests published by the bot! 🎉 

Thank you all for your love and support for my app! ❤️ 
Also, please feel free to reopen a new issue, if a new bug arrives.

**Closed by abhijeetps** 2019-02-04 12:46 UTC
Labels: bug
